runtime: python38
entrypoint: uwsgi --http-socket :8080 --wsgi-file busca.py --callable app --master --processes 1 --threads 2

handlers:
- url: /
  static_files: Busca_sinonimo.html
  upload: Busca_sinonimo.html

- url: /(.*)
  static_files: /\1
  upload: /(.*)
